# See GitHub's docs for more information on this file:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    labels:
      - "dependency-upgrade"
    open-pull-requests-limit: 50

  # Maintain dependencies for NPM modules
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    open-pull-requests-limit: 50
    labels:
      - "dependency-upgrade"
    ignore:
      # Ignore major versions of ESLint greater than 8, as it's still known to be flaky
      - dependency-name: "eslint"
        versions: [">8"]